Task02 - Creating sentence from array
MaraEfimova/ruby_tasks pull request #4
Opened 2023-02-23 11:18 UTC by MaraEfimova

An array with different variables is transformed into a valid string that can only contain numbers, letters, commas (not at the beginning and not at the end) and dash (not at the end). Added error display for specific cases.

2023-02-24 16:33 UTC, kaloyan-yordanov requested changes
@MaraEfimova Few issues here:
- `["  ,This"]` is transformed to`, This.`, and an error should be thrown instead (because of the `,`)
- `["This -  "]` is transformed to`This -.` and an error should be thrown instead (because of the `-`)
- `[]` should have a separate error for empty input, because it is in fact not containing illegal characters
- if you pass `{}` the error should say that the input type is invalid and you expect an Array
- remove `p format_array`
- I don't believe `_` are allowed
- `["asd a", "qwe"]` is returning `Asd aqwe.` which is incorrect, should be `Asd a qwe.`
- is `!format_array.scan(/[a-zA-Z]/).empty?` really needed?
- remove all the `elsif`s, simply rise the errors, if no error is raised - the script will ocntinue to the `format_array = format_array.squeeze(" ")` line anyway

2023-03-13 00:18 UTC, kaloyan-yordanov requested changes

2023-03-13 00:18 UTC, kaloyan-yordanov commented on task02.rb
> +  if arr.empty?
@MaraEfimova There is an unexpected error when the input is `[""]`.

2023-03-13 00:18 UTC, kaloyan-yordanov commented on task02.rb
> +    raise "The input type is invalid, expect an array"
@MaraEfimova In general I wanted some sort of error, e.g. `raise ArgumentError, "Having error class is better"`. It is still throwing a RuntimeError, but we should always use an explicit error class.

2023-03-13 00:18 UTC, kaloyan-yordanov commented on task02.rb
> +  if !format_array.scan(/[^\s\w,-]/).empty? || !format_array.scan(/_/).empty?
@MaraEfimova What are those two validation actually doing? And do we need a separate one for `_`?

2023-03-26 22:46 UTC, kaloyan-yordanov requested changes

2023-03-26 22:46 UTC, kaloyan-yordanov commented on task02.rb
> +  if format_string.nil?
@MaraEfimova `["", ""]` is returning `.`, which is incorrect and should rise an error instead... The same applies for `["    "]`, `["   ", "    "]`, etc.

2023-03-26 22:46 UTC, kaloyan-yordanov commented on task02.rb
> +  format_string = arr.flatten.join(" ").strip!
@MaraEfimova Be careful what the bang method does and returns. This leads to unexpected behavior (e.g. `['me']` throwing an exception).

2023-03-26 22:46 UTC, kaloyan-yordanov commented on task02.rb
> +  if !format_string.scan(/([^\s\w,-]|_)/).empty?
@MaraEfimova What is the purpose of this on?

2023-03-26 22:46 UTC, kaloyan-yordanov commented on task02.rb
> +  if !format_string.scan(/\A[,]/).empty?
@MaraEfimova Can't we just get the first symbol instead of using RegEx here?

2023-03-26 22:46 UTC, kaloyan-yordanov commented on task02.rb
> +  if !format_string.scan(/[,-]\z/).empty?
@MaraEfimova Can't we simply get the last symbol and check it insted of using RegEx?

2023-03-26 22:46 UTC, kaloyan-yordanov commented on task02.rb
> +  format_string.sub!(/[a-zA-Z]/) {|string| string[0].upcase}
@MaraEfimova Why you are using `sub!` here like this?

2023-04-03 13:44 UTC, MaraEfimova commented on task02.rb
> +  format_string.sub!(/[a-zA-Z]/) {|string| string[0].upcase}
Cause sentence could start with dash, so I need change first enterance of letter to uppercase.

2023-04-04 20:05 UTC, kaloyan-yordanov approved these changes
@MaraEfimova This is good to go, please squash and merge it!

2023-04-04 20:25 UTC, merged